name: reusable-workflow
run-name: running a called workflow

on:
  workflow_call:
    secrets:
     token:
      required: true
     variable:
      required: true
    inputs:
      variable1:
        description: "the value is required just for testing purpose"
        type: string
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: running and printing the token value
        env:
          git_token: ${{secrets.GITHUB_TOKEN}}
          variable: ${{secrets.variable1}}
        run: |
          echo "print the statements";
          echo  $git_token
          echo $variable
        
