 name: "another way of composite"
 description: "using composite"

 inputs:
   from-date:
     description: "using from date"
     required: true
     default: "2021/01/25"
    

  runs:
    using: "composite"
    id: v1
    steps:
      - name: "running a composite step"
        run: |
         echo "fetching from the date ${{input.from-date}}"
